### ISSUE TITLE
Mancato plottaggio fulmini 20190521

### ISSUE THREAD

**Issue by mauromussin** [ARPASMR/fulmini#14]
I fulmini del 20190521 non sono stati plottati in modo corretto: la mappa è stata prodotta alle 07:43 UTC e non più aggiornata.
Stessa cosa capita per il 20190522 con fermata alle 07:19 UTC

**Comment by mauromussin** [comment]
Un tentativo di plottaggio usando la funzione gf.graf ha evidenziato un errore anche nel caricamento della mappa RL DTM 20x20
```
Traceback (most recent call last):                                                                                                                                                               
  File "<stdin>", line 1, in <module>                                                                                                                                                            
  File "/usr/src/myapp/gf.py", line 118, in graf                                                                                                                                                 
    ax2.add_wms(wms='http://www.cartografia.servizirl.it/arcgis/services/wms/dtm20_utm_wms/MapServer/WMSServer',layers=['0'])      
```

**Comment by mauromussin** [comment]
il problema è causato dalla indisponibilità totale del WMS di RL o forse dal fatto che è cambiato il nome del Layer.
Per tamponare l'errore occorre fare la seguente modifica
```
 except:                                                                                                                                                                                      
        print("WMS RL non disponibile")                                                                                                                                                          
        try:                                                                                                                                                                                     
            ax2.add_wms(wms='http://www.cartografia.servizirl.it/arcgis/services/wms/dtm20_utm_wms/MapServer/WMSServer',layers=['0'])                                                            
        except:                                                                                                                                                                                  
            print("ERRORE: Nessun WMS RL funzionante") 
```

**Comment by mauromussin** [comment]
problema dovuto a mancanza di autorizzazione del proxy.
Occorre cambiare le variabili di ambiente per consentire passaggio proxy con autenticazione.

**Comment by mauromussin** [comment]
Chiusa perchè il problema non si è ripresentato
