### ISSUE TITLE
DISPLAY error

### ISSUE THREAD

**Issue by mauromussin** [ARPASMR/fulmini#8]
Il container esce con un errore a causa della mancanza del display
`Traceback (most recent call last):
  File "Grafica_fulmini.py", line 48, in <module>
    gf(nf)
  File "Grafica_fulmini.py", line 18, in gf
    fig = plt.figure(num=None, figsize=(22, 16) )
  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 242, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 236, in __init__
    _create_qApp()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 144, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable`

**Comment by mauromussin** [comment]
Modificare con installazione di Pillow e con variabile DISPLAY:0
Prima di ogni istruzione aggiungere 
`import  matplotlib
matplotlib.use('Agg')`
